# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.1.1"
  title: 面向h5和apiserver接口
  description:

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /m/apps/group/api/group_buy_product:
    get:
      description: 获得商品是否在团购活动中
      parameters:
        - name: pid
          type: int
      responses:
        200:
          schema:
            title: 商品是否在团购活动中
            properties:
              is_in_group_buy:
                required: true
                type: boolen
              activity_url:
                required: true
                type: string
  /m/apps/group/api/group_buy_products:
    get:
      description: 批量获得商品是否在团购活动中
      parameters:
        - name: pids
          type: list
      responses:
        200:
          schema:
            title: 商品是否在团购活动中
            properties:
              pid2is_in_group_buy:
                required: true
                type: list
  /m/apps/group/api/group_buy_info:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        获取团购商品信息
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        - $ref: '#/definitions/group_id'
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: Person
            type: object
            properties:
              pid:
                type: int32
                description: 商品id
              group_buy_price:
                description: 团购价
                type: double
              group_id:
                type: string
                description: 团id
              activity_id:
                type: string
                description: 团购活动id
              activity_url:
                required: true
                type: string
  /m/apps/group/api/check_group_buy:
    get:
      description: 下单中的检测
      parameters:
        - name: member_id
          description: 会员id
          type: number
          format: int32
        - $ref: '#/definitions/group_id'
        - name: pid
          description: 商品id
      responses:
        200:
          description: Successful response
          schema:
            title: 检测下单的结果
            type: object
            properties:
              is_success:
                type: boolen
                description: 可否下单
              reason:
                type: string
                description: 失败原因
              pid:
                type: int32
                description: 商品id
              group_buy_price:
                description: 团购价
                type: double
              group_id:
                type: string
                description: 团购活动id
  /m/apps/group/api/order_action:
    put:
      description: apiserver通知订单支付成功
      parameters:
        - name: order_id
          type: string
        - name: member_id
          type: string
        - name: action
          type: string
          description: 参数为'pay'(表示支付成功)或者'cancel'(订单已取消)
        - $ref: '#/definitions/group_id'

  /apps/evaluate/get_product_evaluates_status:
    get:
      description: h5个人中心-待评价订单，获取待评价订单的评价状态
      parameters:
        - name: woid
          type: string
        - name: member_id
          type: string
      responses:
        200:
          description: Successful response
          schema:
            title: data
            type: object
            properties:
              orders:
                type: list
                $ref: "#/definitions/orders"
definitions:
  group_id:
    name: group_id
    description: 团购活动中的团id，来字团购活动页点击参团跳转到编辑订单页提供
    type: string
  activity_url:
    name: activity_url
    description: 团购活动链接
    type: string

  orders:
    type: list
    items:
      $ref: "#/definitions/order"
    description: 所有订单信息

